typography_spectrum: 0.6406857471447438
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.41863408917561173
  lightness: 0.9828119447920471
  saturation: 0.05947238905355334
  rhythmicContrast: 0.39731375547125936
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4526780038140714
analytics:
  google: null
  facebook: null
  twitter: null
name: MoreWillie
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: AGGREGATE MY SHIT
description: THE GRID SUCKS
purpose: []
